import type { SectionId } from "@/lib/store/app-store";

export const SECTION_TITLES: Record<SectionId, string> = {
  dashboard: "Dashboard",
  contacts: "Contacts",
  segments: "Segments",
  campaigns: "Campaigns",
  correspondence: "Correspondence",
  automations: "Automations",
  templates: "Templates",
  channels: "Channels",
  social: "Social Media",
  "ai-assistant": "AI Assistant",
  "ai-campaign-writer": "AI Campaign Writer",
  "ai-message-generator": "AI Message Generator",
  "ai-reply-assistant": "AI Reply Assistant",
  "ai-conversation-summary": "AI Conversation Summary",
  "ai-translator": "AI Translator",
  "ai-classifier": "AI Classifier",
  "ai-automation": "AI Automation",
  "ai-knowledge-base": "AI Knowledge Base",
  "ai-customer-support": "AI Customer Support",
  "ai-campaign-optimization": "AI Campaign Optimization",
  "ai-ab-test": "AI A/B Test Generator",
  "ai-subject-lines": "AI Subject Lines",
  "ai-image-prompt": "AI Creative Assistant",
  "ai-settings": "AI Settings",
  "ai-usage": "AI Usage",
  notifications: "Notifications",
  reports: "Reports",
  api: "API",
  webhooks: "Webhooks",
  team: "Team",
  settings: "Settings",
  admin: "Admin",
};
